"""agregar credenciales y eventos de importacion

Revision ID: 27d8823019dd
Revises: 963e78601998
Create Date: 2026-08-03 09:44:05.709482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d8823019dd'
down_revision = '963e78601998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='fk_api_credential_institution', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_api_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_api_credentials_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institution_api_credentials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_institution_api_credentials_token_hash'), ['token_hash'], unique=True)

    op.create_table('project_import_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('external_project_id', sa.String(length=120), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='fk_import_event_institution', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_import_event_project', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_import_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_import_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_import_events_external_project_id'), ['external_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_import_events_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_import_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_import_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_import_events_result'), ['result'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('project_import_events')
    op.drop_table('institution_api_credentials')
