"""agregar nucleo regional multiinstitucion

Revision ID: 963e78601998
Revises: c43b8abbefe3
Create Date: 2026-08-03 08:36:55.220338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e78601998'
down_revision = 'c43b8abbefe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('circuit', sa.String(length=80), nullable=True),
    sa.Column('regional_directorate', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('responsible_name', sa.String(length=160), nullable=False),
    sa.Column('responsible_email', sa.String(length=160), nullable=False),
    sa.Column('responsible_phone', sa.String(length=40), nullable=True),
    sa.Column('uses_institutional_platform', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('participation_status', sa.String(length=30), server_default='invited', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_circuit'), ['circuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_institutions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_participation_status'), ['participation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_regional_directorate'), ['regional_directorate'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_responsible_email'), ['responsible_email'], unique=False)

    op.create_table('project_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['judges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_history_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_history_to_status'), ['to_status'], unique=False)

    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_judges_institution_id'), ['institution_id'], unique=False)
        batch_op.create_foreign_key('fk_judges_institution', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=30), server_default='regional_manual', nullable=False))
        batch_op.add_column(sa.Column('regional_status', sa.String(length=40), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('external_project_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('external_source', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('source_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('received_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regional_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payload_version', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_regional_status'), ['regional_status'], unique=False)
        batch_op.create_unique_constraint('uq_project_institution_external_id', ['institution_id', 'external_project_id'])
        batch_op.create_foreign_key('fk_projects_category_regional', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_projects_approved_by', 'judges', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_projects_institution', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')

    regional_settings = {
        'school_name': 'ExpoTécnica Regional',
        'school_address': 'Sede regional por definir',
        'school_phone': '+506 0000-0000',
        'school_email': 'coordinacion@expotecnicaregional.local',
        'school_logo_path': '',
        'expo_logo_path': '',
        'expotec_stage': 'Regional',
    }
    for key, value in regional_settings.items():
        op.execute(
            sa.text(
                """
                INSERT INTO system_settings (`key`, `value`, updated_at)
                VALUES (:key, :value, CURRENT_TIMESTAMP)
                ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), updated_at = CURRENT_TIMESTAMP
                """
            ).bindparams(key=key, value=value)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_institution', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_approved_by', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_category_regional', type_='foreignkey')
        batch_op.drop_constraint('uq_project_institution_external_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_projects_regional_status'))
        batch_op.drop_index(batch_op.f('ix_projects_origin'))
        batch_op.drop_index(batch_op.f('ix_projects_institution_id'))
        batch_op.drop_index(batch_op.f('ix_projects_category_id'))
        batch_op.drop_index(batch_op.f('ix_projects_approved_by_id'))
        batch_op.drop_column('payload_version')
        batch_op.drop_column('regional_notes')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('received_at')
        batch_op.drop_column('source_updated_at')
        batch_op.drop_column('external_source')
        batch_op.drop_column('external_project_id')
        batch_op.drop_column('regional_status')
        batch_op.drop_column('origin')
        batch_op.drop_column('category_id')
        batch_op.drop_column('institution_id')

    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_judges_institution', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_judges_institution_id'))
        batch_op.drop_column('institution_id')

    op.drop_table('project_status_history')
    op.drop_table('institutions')
    # ### end Alembic commands ###
