"""esquema base institucional heredado

Revision ID: c43b8abbefe3
Revises: 
Create Date: 2026-08-03 08:35:32.589237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43b8abbefe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_is_active'), ['is_active'], unique=False)

    op.create_table('evaluation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scale_labels', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_types_code'), ['code'], unique=True)

    op.create_table('judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('identity', sa.String(length=40), nullable=True),
    sa.Column('institution', sa.String(length=160), nullable=True),
    sa.Column('previous_expo', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('can_evaluate_documentation', sa.Boolean(), nullable=False),
    sa.Column('can_evaluate_exposition', sa.Boolean(), nullable=False),
    sa.Column('can_evaluate_english', sa.Boolean(), nullable=False),
    sa.Column('category_scope', sa.String(length=40), nullable=False),
    sa.Column('registration_notes', sa.Text(), nullable=True),
    sa.Column('registered_from_public_form', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('attendance_token', sa.String(length=64), nullable=True),
    sa.Column('attendance_confirmed', sa.Boolean(), nullable=True),
    sa.Column('needs_parking', sa.Boolean(), nullable=False),
    sa.Column('attendance_responded_at', sa.DateTime(), nullable=True),
    sa.Column('attendance_invitation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('attendance_invitation_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_token'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judges_department'), ['department'], unique=False)

    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_code'), ['code'], unique=True)

    op.create_table('project_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_types_code'), ['code'], unique=True)

    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_name'), ['name'], unique=True)

    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(length=140), nullable=False),
    sa.Column('actor_email', sa.String(length=160), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('thematic_axes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thematic_axes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thematic_axes_code'), ['code'], unique=True)

    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('identity_number', sa.String(length=40), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutors_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutors_identity_number'), ['identity_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_tutors_is_active'), ['is_active'], unique=False)

    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshops_name'), ['name'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rubric_1_evaluation_type_id', sa.Integer(), nullable=True),
    sa.Column('rubric_2_evaluation_type_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_1_evaluation_type_id'], ['evaluation_types.id'], ),
    sa.ForeignKeyConstraint(['rubric_2_evaluation_type_id'], ['evaluation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_code'), ['code'], unique=True)

    op.create_table('rubric_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=180), nullable=True),
    sa.Column('section_sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_type_id'], ['evaluation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubric_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubric_criteria_evaluation_type_id'), ['evaluation_type_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_level_id'), ['level_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('team_name', sa.String(length=180), nullable=False),
    sa.Column('representative_name', sa.String(length=120), nullable=False),
    sa.Column('representative_email', sa.String(length=120), nullable=False),
    sa.Column('representative_phone', sa.String(length=40), nullable=True),
    sa.Column('institution_name', sa.String(length=180), nullable=True),
    sa.Column('grade_level', sa.String(length=60), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('thematic_axis_id', sa.Integer(), nullable=True),
    sa.Column('project_type_id', sa.Integer(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('advisor_name', sa.String(length=120), nullable=True),
    sa.Column('advisor_identity', sa.String(length=40), nullable=True),
    sa.Column('advisor_birth_date', sa.Date(), nullable=True),
    sa.Column('advisor_gender', sa.String(length=20), nullable=True),
    sa.Column('advisor_specialty', sa.String(length=140), nullable=True),
    sa.Column('advisor_email', sa.String(length=120), nullable=True),
    sa.Column('advisor_phone', sa.String(length=40), nullable=True),
    sa.Column('mentor_name', sa.String(length=120), nullable=True),
    sa.Column('mentor_identity', sa.String(length=40), nullable=True),
    sa.Column('mentor_birth_date', sa.Date(), nullable=True),
    sa.Column('mentor_gender', sa.String(length=20), nullable=True),
    sa.Column('mentor_specialty', sa.String(length=140), nullable=True),
    sa.Column('mentor_email', sa.String(length=120), nullable=True),
    sa.Column('mentor_phone', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_objective', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('required_resources', sa.Text(), nullable=True),
    sa.Column('requirements_items_json', sa.Text(), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_end_date', sa.Date(), nullable=True),
    sa.Column('requirements_summary', sa.Text(), nullable=True),
    sa.Column('requirements_other', sa.String(length=255), nullable=True),
    sa.Column('requirements_status', sa.String(length=40), nullable=False),
    sa.Column('requirements_notes', sa.Text(), nullable=True),
    sa.Column('requirements_current_ok', sa.Boolean(), nullable=False),
    sa.Column('requirements_outlets_ok', sa.Boolean(), nullable=False),
    sa.Column('requirements_internet_ok', sa.Boolean(), nullable=False),
    sa.Column('requirements_water_ok', sa.Boolean(), nullable=False),
    sa.Column('requirements_other_ok', sa.Boolean(), nullable=False),
    sa.Column('requirements_resources_ok', sa.Boolean(), nullable=False),
    sa.Column('project_document_path', sa.String(length=300), nullable=True),
    sa.Column('project_logo_path', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logistics_status', sa.String(length=40), nullable=False),
    sa.Column('logistics_notes', sa.Text(), nullable=True),
    sa.Column('logistics_document_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_logo_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_photos_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_registration_form_signed_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_student_consents_signed_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_cedula_tutor_ok', sa.Boolean(), nullable=False),
    sa.Column('logistics_requirements_reviewed_ok', sa.Boolean(), nullable=False),
    sa.Column('consent_terms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['thematic_axis_id'], ['thematic_axes.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_logistics_status'), ['logistics_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_type_id'), ['project_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_requirements_status'), ['requirements_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_specialty_id'), ['specialty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_thematic_axis_id'), ['thematic_axis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tutor_id'), ['tutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('can_evaluate_documentation', sa.Boolean(), nullable=False),
    sa.Column('can_evaluate_exposition', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'project_id', name='uq_assignment_judge_project')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_status'), ['status'], unique=False)

    op.create_table('project_document_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_path', sa.String(length=300), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_document_path', sa.String(length=300), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['judges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_document_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_document_revisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_document_revisions_status'), ['status'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('identity_number', sa.String(length=40), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=140), nullable=True),
    sa.Column('section_name', sa.String(length=30), nullable=True),
    sa.Column('has_dining_scholarship', sa.Boolean(), nullable=False),
    sa.Column('participates_in_english', sa.Boolean(), nullable=False),
    sa.Column('consent_signed_ok', sa.Boolean(), nullable=False),
    sa.Column('cedula_copies_ok', sa.Boolean(), nullable=False),
    sa.Column('cedula_encargado_ok', sa.Boolean(), nullable=False),
    sa.Column('cedula_estudiante_ok', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_specialty_id'), ['specialty_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_member_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_type', sa.String(length=60), nullable=False),
    sa.Column('criteria_1', sa.Integer(), nullable=True),
    sa.Column('criteria_2', sa.Integer(), nullable=True),
    sa.Column('criteria_3', sa.Integer(), nullable=True),
    sa.Column('criteria_4', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_member_id'], ['project_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'project_id', 'evaluation_type', 'project_member_id', name='uq_eval_type_per_judge_project_member')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_evaluation_type'), ['evaluation_type'], unique=False)

    op.create_table('project_member_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_member_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_changes_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_member_changes_project_id'), ['project_id'], unique=False)

    op.create_table('project_member_edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=120), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['judges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_member_edit_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_edit_requests_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_member_edit_requests_project_id'), ['project_id'], unique=False)

    op.create_table('evaluation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('rubric_criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['rubric_criterion_id'], ['rubric_criteria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'rubric_criterion_id', name='uq_evaluation_score_criterion')
    )
    with op.batch_alter_table('evaluation_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_scores_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_scores_rubric_criterion_id'), ['rubric_criterion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_scores_rubric_criterion_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_scores_evaluation_id'))

    op.drop_table('evaluation_scores')
    with op.batch_alter_table('project_member_edit_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_edit_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_member_edit_requests_member_id'))

    op.drop_table('project_member_edit_requests')
    with op.batch_alter_table('project_member_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_changes_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_member_changes_member_id'))

    op.drop_table('project_member_changes')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluation_type'))

    op.drop_table('evaluations')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('project_document_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_document_revisions_status'))
        batch_op.drop_index(batch_op.f('ix_project_document_revisions_project_id'))

    op.drop_table('project_document_revisions')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_status'))

    op.drop_table('assignments')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_projects_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_projects_thematic_axis_id'))
        batch_op.drop_index(batch_op.f('ix_projects_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_projects_section_id'))
        batch_op.drop_index(batch_op.f('ix_projects_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_projects_project_type_id'))
        batch_op.drop_index(batch_op.f('ix_projects_logistics_status'))
        batch_op.drop_index(batch_op.f('ix_projects_is_active'))
        batch_op.drop_index(batch_op.f('ix_projects_category'))
        batch_op.drop_index(batch_op.f('ix_projects_campaign_id'))

    op.drop_table('projects')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_level_id'))

    op.drop_table('sections')
    with op.batch_alter_table('rubric_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubric_criteria_evaluation_type_id'))

    op.drop_table('rubric_criteria')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_code'))

    op.drop_table('categories')
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshops_name'))

    op.drop_table('workshops')
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutors_is_active'))
        batch_op.drop_index(batch_op.f('ix_tutors_identity_number'))
        batch_op.drop_index(batch_op.f('ix_tutors_email'))

    op.drop_table('tutors')
    with op.batch_alter_table('thematic_axes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thematic_axes_code'))

    op.drop_table('thematic_axes')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_action'))

    op.drop_table('system_audit_logs')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_name'))

    op.drop_table('specialties')
    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_types_code'))

    op.drop_table('project_types')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_code'))

    op.drop_table('levels')
    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judges_department'))

    op.drop_table('judges')
    with op.batch_alter_table('evaluation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_types_code'))

    op.drop_table('evaluation_types')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_is_active'))

    op.drop_table('campaigns')
    # ### end Alembic commands ###
