from flask import Blueprint

from app.controllers import admin_controller

admin_bp = Blueprint("admin", __name__, url_prefix="/admin")

admin_bp.add_url_rule("/action", view_func=admin_controller.perform_action, methods=["POST"])
admin_bp.add_url_rule("/panel", view_func=admin_controller.overview, methods=["GET"])
admin_bp.add_url_rule("/asignaciones", view_func=admin_controller.assignments_page, methods=["GET"])
admin_bp.add_url_rule("/jueces/evaluacion", view_func=admin_controller.judge_pool_page, methods=["GET"])
admin_bp.add_url_rule("/jueces", view_func=admin_controller.judges_page, methods=["GET"])
admin_bp.add_url_rule("/permisos", view_func=admin_controller.permissions_page, methods=["GET"])
admin_bp.add_url_rule("/categorias", view_func=admin_controller.categories_page, methods=["GET"])
admin_bp.add_url_rule("/campanas", view_func=admin_controller.campaigns_page, methods=["GET"])
admin_bp.add_url_rule("/academico", view_func=admin_controller.academic_page, methods=["GET"])
admin_bp.add_url_rule("/rubricas", view_func=admin_controller.rubrics_page, methods=["GET"])
admin_bp.add_url_rule("/proyectos", view_func=admin_controller.projects_page, methods=["GET"])
admin_bp.add_url_rule("/proyectos/recordatorio", view_func=admin_controller.logistics_reminder_page, methods=["GET"])
admin_bp.add_url_rule("/evaluaciones", view_func=admin_controller.evaluations_page, methods=["GET"])
admin_bp.add_url_rule("/documentos", view_func=admin_controller.documents_page, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>", view_func=admin_controller.evaluation_report_project_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>/pdf", view_func=admin_controller.evaluation_report_project_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>/descargar", view_func=admin_controller.evaluation_report_project_download, methods=["GET"])
admin_bp.add_url_rule("/actas/general", view_func=admin_controller.evaluation_report_all_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/general/pdf", view_func=admin_controller.evaluation_report_all_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/general/descargar", view_func=admin_controller.evaluation_report_all_download, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>", view_func=admin_controller.evaluation_report_judge_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>/pdf", view_func=admin_controller.evaluation_report_judge_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>/descargar", view_func=admin_controller.evaluation_report_judge_download, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion", view_func=admin_controller.participation_certificates_preview, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion/pdf", view_func=admin_controller.participation_certificates_pdf, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion/descargar", view_func=admin_controller.participation_certificates_download, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>", view_func=admin_controller.project_certificates_preview, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>/pdf", view_func=admin_controller.project_certificates_pdf, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>/descargar", view_func=admin_controller.project_certificates_download, methods=["GET"])
admin_bp.add_url_rule("/smtp", view_func=admin_controller.smtp_page, methods=["GET"])
admin_bp.add_url_rule("/institucion", view_func=admin_controller.institution_page, methods=["GET"])
admin_bp.add_url_rule("/mantenimiento", view_func=admin_controller.maintenance_page, methods=["GET"])
admin_bp.add_url_rule("/base-datos", view_func=admin_controller.database_page, methods=["GET"])
admin_bp.add_url_rule("/base-datos/respaldos/<path:filename>/descargar", view_func=admin_controller.database_backup_download, methods=["GET"])
admin_bp.add_url_rule("/git", view_func=admin_controller.gitops_page, methods=["GET"])
admin_bp.add_url_rule("/bitacora", view_func=admin_controller.logs_page, methods=["GET"])
